---
- name: Create systemd user service
  block:
    - name: Create systemd user service files for sync_folders
      ansible.builtin.template:
        src: vm_share_helper.service.j2
        dest: "{{ ansible_env.HOME }}/.config/systemd/user/vm_share_helper_{{ sync_item.unison_name }}.service"
        mode: "0700"
      with_items: "{{ vm_share_helper_sync_folders }}"
      loop_control:
        loop_var: sync_item
      notify: Reload systemd user services

    - name: Create systemd timer files for sync_folders
      ansible.builtin.template:
        src: vm_share_helper.timer.j2
        dest: "{{ ansible_env.HOME }}/.config/systemd/user/vm_share_helper_{{ sync_item.unison_name }}.timer"
        mode: "0700"
      with_items: "{{ vm_share_helper_sync_folders }}"
      loop_control:
        loop_var: sync_item
      notify: Reload systemd user services

    - name: Enable and start sync_folders timer
      ansible.builtin.systemd_service:
        name: vm_share_helper_{{ sync_item.unison_name }}.timer
        state: started
        enabled: true
        masked: false
        scope: user
      with_items: "{{ sync_folders }}"
      loop_control:
        loop_var: sync_item
