---
- name: Reload systemd user services
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{ ansible_uid }}/bus
  become_user: "{{ ansible_user }}"
  become: true
