---
- name: Converge
  hosts: all

  vars:
    ansible_user: vagrant

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true
      when: ansible_os_family == 'Debian'

  roles:
    - role: pluggero.vm_share_helper
