---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: "pluggero/${MOLECULE_VAGRANT_BOX:-debian12}-ansible"
    box_version: "${MOLECULE_VAGRANT_BOX_VERSION:-1.4.0}"
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
