---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: "${MOLECULE_VAGRANT_BOX:-pluggero/debian12-ansible}"
    box_version: "${MOLECULE_VAGRANT_BOX_VERSION:-1.3.0}"
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
